In [17]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from my_ml_kit import *

# =========================
# Classification Models
# =========================

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    HistGradientBoostingClassifier,
    VotingClassifier,
    StackingClassifier,
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier


# =========================
# Regression Models
# =========================

from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
)

from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor,
    HistGradientBoostingRegressor,
    VotingRegressor,
    StackingRegressor,
)

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [18]:
df = sns.load_dataset('titanic')
data = df.drop(['deck','alive','who','adult_male','class','embark_town'],axis=1)
data['alone'] = data['alone'].astype(int)

X = data.drop('survived', axis=1)
y = data['survived']

data_split = make_data_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42,
)

numeric_features = ['age', 'fare', 'sibsp', 'parch','alone']
categorical_features = ['pclass', 'sex', 'embarked']

In [19]:
numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [20]:
classification_basic_models = {
    "logistic_regression": LogisticRegression(),
    "knn_classifier": KNeighborsClassifier(),
    "decision_tree_classifier": DecisionTreeClassifier(),
    "gaussian_nb": GaussianNB(),
}
classification_intermediate_models = {
    "random_forest": RandomForestClassifier(),
    "extra_trees": ExtraTreesClassifier(),
    "gradient_boosting": GradientBoostingClassifier(),
    "adaboost": AdaBoostClassifier(),
}
classification_advanced_models = {
    "xgboost": XGBClassifier(),
    "lightgbm": LGBMClassifier(),
    "catboost": CatBoostClassifier(verbose=0),
    "svc_rbf": SVC(probability=True),
}

regression_basic_models = {
    "linear_regression": LinearRegression(),
    "ridge": Ridge(),
    "lasso": Lasso(),
    "knn_regressor": KNeighborsRegressor(),
    "decision_tree_regressor": DecisionTreeRegressor(),
}
regression_intermediate_models = {
    "random_forest_regressor": RandomForestRegressor(),
    "extra_trees_regressor": ExtraTreesRegressor(),
    "gradient_boosting_regressor": GradientBoostingRegressor(),
    "adaboost_regressor": AdaBoostRegressor(),
}
regression_advanced_models = {
    "xgboost_regressor": XGBRegressor(),
    "lightgbm_regressor": LGBMRegressor(),
    "catboost_regressor": CatBoostRegressor(verbose=0),
    "svr_rbf": SVR(),
}

In [21]:
results, trained_pipes, predictions = run_model_candidates(
    models=classification_basic_models,
    preprocessor=preprocessor,
    **data_split,
    task_type="classification",
)

display(compare_results(results))

Running: logistic_regression
Running: knn_classifier
Running: decision_tree_classifier
Running: gaussian_nb

,name,task_type,cv_accuracy,cv_accuracy_std,cv_f1,cv_f1_std,cv_precision,cv_precision_std,cv_recall,cv_recall_std,cv_roc_auc,cv_roc_auc_std,test_accuracy,test_f1,test_precision,test_recall,test_roc_auc
0,knn_classifier,classification,0.806264,0.028381,0.736682,0.047974,0.764519,0.026250,0.714411,0.079906,0.851255,0.027827,0.815642,0.744186,0.800000,0.695652,0.850329
1,gaussian_nb,classification,0.785167,0.018495,0.728319,0.021596,0.708102,0.027165,0.751044,0.032792,0.836095,0.032626,0.765363,0.695652,0.695652,0.695652,0.830567
2,logistic_regression,classification,0.793627,0.026135,0.720169,0.048026,0.747602,0.030728,0.699865,0.078525,0.855856,0.023115,0.815642,0.740157,0.810345,0.681159,0.850461
3,decision_tree_classifier,classification,0.775377,0.032525,0.701889,0.046452,0.714318,0.041797,0.692593,0.065346,0.764575,0.035361,0.821229,0.761194,0.784615,0.739130,0.794664

In [11]:
from sklearn.datasets import load_diabetes

In [12]:
data2 = load_diabetes()
data2

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [13]:
X_2 = pd.DataFrame(data2.data,columns=data2.feature_names)
y_2 = pd.Series(data2.target)

In [14]:
data_split_2 = make_data_split(
    X_2,
    y_2,
    test_size=0.2,
    random_state=42,
)

In [8]:
numeric_cols = X_2.columns

preprocessor_2 = ColumnTransformer([
    ("num", StandardScaler(), numeric_cols)
])

In [10]:
results, trained_pipes, predictions = run_model_candidates(
    models=regression_basic_models,
    preprocessor=preprocessor_2,
    **data_split_2,
    task_type="regression",
)

display(compare_results(results))

Running: linear_regression
Running: ridge
Running: lasso
Running: knn_regressor
Running: decision_tree_regressor

,name,task_type,cv_mean_squared_error,cv_mean_squared_error_std,cv_root_mean_squared_error,cv_root_mean_squared_error_std,cv_mean_absolute_error,cv_mean_absolute_error_std,cv_r2,cv_r2_std,test_mse,test_rmse,test_mae,test_r2
0,lasso,regression,3130.458031,277.826483,55.894280,2.507477,45.560503,2.441967,0.454135,0.125346,2824.568094,53.146666,42.802984,0.466877
1,ridge,regression,3135.526209,331.651040,55.916494,2.978572,45.482945,2.912430,0.451266,0.138783,2892.014566,53.777454,42.811999,0.454147
2,linear_regression,regression,3143.015307,355.466814,55.972086,3.184478,45.543329,3.114136,0.449256,0.144095,2900.193628,53.853446,42.794095,0.452603
3,knn_regressor,regression,3967.905557,334.027302,62.936022,2.638698,50.358865,2.636946,0.317546,0.101364,3047.449888,55.203713,42.777528,0.424809
4,decision_tree_regressor,regression,6618.655694,342.579543,81.327933,2.103077,64.032193,1.944607,-0.161308,0.269182,4910.584270,70.075561,55.168539,0.073151