In [2]:
import pandas as pd
import numpy as np

df_csv=pd.read_csv('california_housing_train.csv')

df_csv.head()
df_csv.tail()
df_csv.sample(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
12050,-121.42,38.63,42.0,1385.0,273.0,740.0,274.0,2.6055,78000.0
1536,-117.21,32.85,26.0,2012.0,315.0,872.0,335.0,5.4067,277500.0
5260,-118.14,34.06,39.0,2390.0,444.0,1246.0,422.0,3.7857,245700.0

In [6]:
import sqlite3

db_path=r"C:\Users\sdh08\PycharmProjects\PythonProject1\개인\mydb.db"

conn=sqlite3.connect(db_path)

cur=conn.cursor()

cur.execute("""
     create table if not exists users(
        id integer primary key autoincrement
       ,name text
       , age integer
      , email text
     )

""")

sample_data=[('test',35,'user1@aaa.com' )
        ,('hong',20, 'user2@aaa.com')
        ,('kim',10,'user3@aaa.com')
        ,('park',15, 'user4@aaa.com')
        ,('lee',25,'user5@aaa.com')
        ,('kang',30,'user6@aaa.com')
        ]

cur.executemany(" insert into users (name, age, email) values(?,?,?)", sample_data)

conn.commit()

conn.close()

In [7]:
import sqlite3
from sqlalchemy import create_engine
import pandas as pd

engine=create_engine('sqlite:///mydb.db')

with engine.connect() as conn:
     query="select * from users"
     df=pd.read_sql(query, conn)

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import seaborn as sns

In [9]:
pima_columns = ['pregnancies', 'glucose', 'blood_pressure', 'skin_thickness',
                'insulin', 'bmi', 'diabetes_pedigree_function', 'age', 'outcome']
pima_data_url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'

# names 파라미터를 사용하여 컬럼명 지정
df = pd.read_csv(pima_data_url, names=pima_columns)

In [10]:
display(df[['bmi','age']])

      bmi  age
0    33.6   50
1    26.6   31
2    23.3   32
3    28.1   21
4    43.1   33
..    ...  ...
763  32.9   63
764  36.8   27
765  26.2   30
766  30.1   47
767  30.4   23

[768 rows x 2 columns]

In [12]:
display(df[df['age']>=50].index)

Index([  0,   8,   9,  12,  13,  14,  21,  24,  28,  30,  39,  43,  53,  67,
        93, 115, 123, 129, 140, 148, 186, 204, 206, 207, 212, 221, 223, 236,
       259, 263, 274, 278, 284, 285, 294, 299, 319, 344, 361, 362, 363, 375,
       388, 401, 453, 456, 458, 459, 473, 475, 479, 487, 489, 495, 498, 509,
       512, 516, 517, 519, 537, 542, 546, 548, 552, 557, 560, 579, 582, 584,
       588, 603, 614, 618, 642, 658, 660, 666, 674, 676, 684, 702, 717, 719,
       734, 749, 757, 759, 763],
      dtype='int64')

In [15]:
df.loc[0:2,['age','bmi']]

   age   bmi
0   50  33.6
1   31  26.6
2   32  23.3

In [29]:
df[df['pregnancies']<3]['pregnancies'].value_counts().sort_index()

pregnancies
0    111
1    135
2    103
Name: count, dtype: int64

In [33]:
bin = [0,10,20,30,40,float('inf')]
label = ['d0','d10','d20','d30','others']


df['age_level'] = pd.cut(df['age'], bins=bin, labels=label)
df['age_level'].value_counts().sort_index()

age_level
d0          0
d10         0
d20       417
d30       157
others    194
Name: count, dtype: int64