In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
pima_columns = ['pregnancies', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin', 'bmi', 'diabetes_pedigree_function', 'age', 'outcome']
pima_data_url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
pima_df = pd.read_csv(pima_data_url,names=pima_columns)

In [4]:
X = pima_df.drop('outcome', axis=1)
y = pima_df['outcome']

In [8]:
# print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: outcome, Length: 768, dtype: int64

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [46]:
from pandas.core.dtypes import astype
from sklearn.datasets import load_diabetes
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

diabetes = load_diabetes()

In [47]:
diabetes_df = pd.DataFrame(data = diabetes.data, columns = diabetes.feature_names )

In [49]:
diabetes_df['target']=diabetes.target

In [50]:
X = diabetes_df.drop(columns='target')
y = diabetes_df['target']

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [71]:
X_train.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000
mean,0.001442,0.000184,0.001736,0.001179,-0.000556,-0.000806,-0.000989,0.000377,0.001216,0.001891
std,0.046334,0.047644,0.047275,0.048469,0.047786,0.047631,0.047044,0.047790,0.047828,0.048380
min,-0.107226,-0.044642,-0.089197,-0.112399,-0.108893,-0.115613,-0.102307,-0.076395,-0.126097,-0.137767
25%,-0.030942,-0.044642,-0.032073,-0.036656,-0.035968,-0.032629,-0.032356,-0.039493,-0.033246,-0.030072
50%,0.009016,-0.044642,-0.005128,-0.005670,-0.004321,-0.004132,-0.006584,-0.002592,-0.000612,0.003064
75%,0.038076,0.050680,0.032595,0.035644,0.025950,0.027183,0.026550,0.034309,0.033654,0.032059
max,0.110727,0.050680,0.160855,0.132044,0.153914,0.198788,0.181179,0.185234,0.133597,0.135612

In [65]:
X_train.loc[84]

age    0.001751
sex   -0.044642
bmi   -0.039618
bp    -0.100934
s1    -0.029088
s2    -0.030124
s3     0.044958
s4    -0.050195
s5    -0.068332
s6    -0.129483
Name: 84, dtype: float64

In [70]:
X_train.index[X_train['age']>=50]

Index([], dtype='int64')

In [72]:
pima_df=pd.read_csv(pima_data_url, names=pima_columns)

pima_df.head()
pima_df.tail()
pima_df.sample(3)

pima_df.info()


X=pima_df.drop(columns='outcome')
y=pima_df['outcome']

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pregnancies                 768 non-null    int64
 1   glucose                     768 non-null    int64
 2   blood_pressure              768 non-null    int64
 3   skin_thickness              768 non-null    int64
 4   insulin                     768 non-null    int64
 5   bmi                         768 non-null    float64
 6   diabetes_pedigree_function  768 non-null    float64
 7   age                         768 non-null    int64
 8   outcome                     768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [73]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [74]:
X_train[X_train['age']>=50].sort_index()

,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree_function,age
0,6,148,72,35,0,33.6,0.627,50
8,2,197,70,45,543,30.5,0.158,53
9,8,125,96,0,0,0.0,0.232,54
12,10,139,80,0,0,27.1,1.441,57
14,5,166,72,19,175,25.8,0.587,51
...,...,...,...,...,...,...,...,...
717,10,94,72,18,0,23.1,0.595,56
719,5,97,76,27,0,35.6,0.378,52
749,6,162,62,0,0,24.3,0.178,50
757,0,123,72,0,0,36.3,0.258,52
759,6,190,92,0,0,35.5,0.278,66

In [75]:
X_train['age'] = X_train['age'].astype('string')

In [76]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 614 entries, 353 to 107
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pregnancies                 614 non-null    int64
 1   glucose                     614 non-null    int64
 2   blood_pressure              614 non-null    int64
 3   skin_thickness              614 non-null    int64
 4   insulin                     614 non-null    int64
 5   bmi                         614 non-null    float64
 6   diabetes_pedigree_function  614 non-null    float64
 7   age                         614 non-null    string
dtypes: float64(2), int64(5), string(1)
memory usage: 43.2 KB

In [79]:
X_train.rename(columns={'age':'nai'},inplace=True)

In [80]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 614 entries, 353 to 107
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pregnancies                 614 non-null    int64
 1   glucose                     614 non-null    int64
 2   blood_pressure              614 non-null    int64
 3   skin_thickness              614 non-null    int64
 4   insulin                     614 non-null    int64
 5   bmi                         614 non-null    float64
 6   diabetes_pedigree_function  614 non-null    float64
 7   nai                         614 non-null    string
dtypes: float64(2), int64(5), string(1)
memory usage: 43.2 KB